plugins { id 'com.android.application' }

android {
    namespace 'com.namiwin.salesgateway'
    compileSdk 35

    defaultConfig {
        applicationId 'com.namiwin.salesgateway'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '0.3.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
