plugins { id 'com.android.application' }

android {
    namespace 'com.namiwin.salesgateway'
    compileSdk 35

    defaultConfig {
        applicationId 'com.namiwin.salesgateway'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '0.4.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
