const fa=n=>new Intl.NumberFormat('fa-IR').format(n);const irr=n=>`${fa(n)} ریال`;const now=new Date();
const stages=['سرنخ جدید','تماس اولیه','بازدید','پیش‌فاکتور','مذاکره','جلسه قرارداد'];
const state={accounts:[
{id:'a1',name:'شرکت سپاهان سازه',type:'سازنده',phone:'09131111111',city:'اصفهان',source:'معرف',notes:'پروژه‌های نما و در و پنجره',contacts:[{name:'مهندس رضایی',role:'مدیر پروژه',mobile:'09132222222'},{name:'آقای محمودی',role:'مسئول خرید',mobile:'09133333333'}]},
{id:'a2',name:'گروه معماری آرمان',type:'معمار',phone:'09134444444',city:'اصفهان',source:'اینستاگرام',notes:'تمرکز روی پروژه‌های لوکس',contacts:[{name:'مهندس احمدی',role:'معمار',mobile:'09135555555'}]},
{id:'a3',name:'شرکت دیبا ساخت',type:'انبوه‌ساز',phone:'09136666666',city:'اصفهان',source:'بازاریابی',notes:'',contacts:[{name:'مهندس کریمی',role:'مدیرعامل',mobile:'09137777777'}]}
],opps:[
{id:'o1',account:'a1',title:'مجتمع مسکونی سپاهان‌شهر',stage:'مذاکره',amount:32500000000,prob:70,next:'جلسه نهایی قیمت',due:'امروز ۱۶:۳۰',lastDays:2,hot:true},
{id:'o2',account:'a2',title:'ویلای صفه',stage:'پیش‌فاکتور',amount:14800000000,prob:45,next:'پیگیری پیش‌فاکتور',due:'فردا ۱۰:۰۰',lastDays:4},
{id:'o3',account:'a3',title:'برج اداری چهارباغ',stage:'بازدید',amount:51000000000,prob:30,next:'دریافت نقشه نما',due:'امروز ۱۲:۰۰',lastDays:8},
{id:'o4',account:'a1',title:'ساختمان مرداویج',stage:'جلسه قرارداد',amount:22100000000,prob:85,next:'اصلاح بند پرداخت',due:'امروز ۱۸:۰۰',lastDays:1,hot:true},
{id:'o5',account:'a3',title:'پروژه کاوه',stage:'تماس اولیه',amount:9600000000,prob:15,next:'تماس با مدیر پروژه',due:'عقب‌افتاده',lastDays:10},
{id:'o6',account:'a2',title:'رستوران جلفا',stage:'سرنخ جدید',amount:4800000000,prob:10,next:'تماس اول',due:'امروز ۱۴:۰۰',lastDays:0}
],activities:[
{id:'t1',time:'۱۰:۳۰',account:'a3',subject:'دریافت نقشه برج چهارباغ',type:'تماس',overdue:false},
{id:'t2',time:'۱۲:۰۰',account:'a2',subject:'پیگیری پیش‌فاکتور ویلای صفه',type:'پیگیری',overdue:false},
{id:'t3',time:'۱۴:۰۰',account:'a2',subject:'تماس اولیه رستوران جلفا',type:'تماس',overdue:false},
{id:'t4',time:'۱۶:۳۰',account:'a1',subject:'جلسه نهایی قیمت سپاهان‌شهر',type:'جلسه',overdue:false},
{id:'t5',time:'گذشته',account:'a3',subject:'تماس مجدد پروژه کاوه',type:'تماس',overdue:true}
],projects:[
{id:'p1',account:'a1',title:'ساختمان حکیم نظامی',stage:'تولید',progress:6,total:16,amount:18700000000},
{id:'p2',account:'a3',title:'مجتمع آپادانا',stage:'اندازه‌گیری نهایی',progress:5,total:16,amount:27600000000},
{id:'p3',account:'a2',title:'ویلای ناژوان',stage:'نصب',progress:10,total:16,amount:11900000000}
]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const account=id=>state.accounts.find(x=>x.id===id);
function nav(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const map={dashboard:['مرکز فرمان فروش','تصمیم‌های امروز، بدون گم‌شدن هیچ پیگیری'],pipeline:['پایپ‌لاین فروش','فرصت‌ها را بر اساس مرحله، ارزش و اقدام بعدی مدیریت کن'],customers:['مشتریان','پرونده ۳۶۰ درجه هر کارفرما، سازنده و معمار'],projects:['پروژه‌ها','اجرای پروژه بعد از Won شدن فروش'],activities:['مرکز پیگیری','تماس، جلسه و Next Action در یک صف کاری'],reports:['گزارش‌ها','تصمیم مدیریتی بر اساس داده واقعی']};$('#pageTitle').textContent=map[view][0];$('#pageSub').textContent=map[view][1]}
$$('.nav-item').forEach(b=>b.onclick=()=>nav(b.dataset.view));$$('[data-goto]').forEach(b=>b.onclick=()=>nav(b.dataset.goto));
function renderKPIs(){const pipe=state.opps.reduce((s,o)=>s+o.amount,0),weighted=state.opps.reduce((s,o)=>s+o.amount*o.prob/100,0),over=state.activities.filter(x=>x.overdue).length;const items=[['ارزش پایپ‌لاین',irr(pipe),'↑ ۱۲٪'],['Weighted Pipeline',irr(Math.round(weighted)),'بر اساس احتمال'],['فرصت داغ',fa(state.opps.filter(x=>x.hot).length),'اولویت بالا'],['پیگیری امروز',fa(state.activities.filter(x=>!x.overdue).length),'برنامه امروز'],['عقب‌افتاده',fa(over),over?'نیاز به اقدام':'بدون تاخیر','warn'],['پروژه فعال',fa(state.projects.length),'در حال اجرا']];$('#kpis').replaceChildren(...items.map(([l,v,s,c])=>{const d=document.createElement('div');d.className='kpi';const a=document.createElement('span');a.className='label';a.textContent=l;const b=document.createElement('strong');b.textContent=v;const sm=document.createElement('small');if(c)sm.className=c;sm.textContent=s;d.append(a,b,sm);return d}))}
function renderMiniPipeline(){const root=$('#miniPipeline');root.replaceChildren(...stages.map(st=>{const arr=state.opps.filter(o=>o.stage===st),sum=arr.reduce((s,o)=>s+o.amount,0);const d=document.createElement('div');d.className='mini-stage';const s=document.createElement('span');s.textContent=st;const b=document.createElement('b');b.textContent=fa(arr.length)+' فرصت';const p=document.createElement('div');p.className='progress';const i=document.createElement('i');i.style.width=Math.min(100,(sum/51000000000)*100)+'%';p.append(i);const small=document.createElement('span');small.textContent=irr(sum);d.append(s,b,p,small);return d}))}
function renderActivities(){const root=$('#todayActivities'),arr=[...state.activities].sort((a,b)=>Number(b.overdue)-Number(a.overdue));root.replaceChildren(...arr.map(x=>{const d=document.createElement('div');d.className='activity';const t=document.createElement('div');t.className='time';t.textContent=x.time;const m=document.createElement('div');const b=document.createElement('b');b.textContent=x.subject;const p=document.createElement('p');p.textContent=`${x.type} • ${account(x.account).name}`;m.append(b,p);const btn=document.createElement('button');btn.className='secondary';btn.textContent='ثبت نتیجه';btn.onclick=()=>openResult(x);d.append(t,m,btn);return d}));$('#overdueCount').textContent=`${fa(state.activities.filter(x=>x.overdue).length)} عقب‌افتاده`}
function renderRisk(){const risks=state.opps.filter(o=>o.lastDays>=7||!o.next).sort((a,b)=>b.lastDays-a.lastDays);$('#riskList').replaceChildren(...risks.map(o=>{const d=document.createElement('div');d.className='risk-item';const m=document.createElement('div');const b=document.createElement('b');b.textContent=o.title;const p=document.createElement('p');p.textContent=`${account(o.account).name} • ${o.lastDays} روز بدون فعالیت`;m.append(b,p);const s=document.createElement('span');s.className='risk-score';s.textContent='⚠ پیگیری';d.append(m,s);return d}))}
function renderProjectsStrip(){const mk=p=>{const d=document.createElement('div');d.className='project-card';const h=document.createElement('h3');h.textContent=p.title;const a=document.createElement('p');a.textContent=account(p.account).name;const b=document.createElement('p');b.textContent=irr(p.amount);const st=document.createElement('div');st.className='project-stage';st.textContent=`مرحله: ${p.stage} • ${fa(p.progress)}/${fa(p.total)}`;d.append(h,a,b,st);return d};$('#projectStrip').replaceChildren(...state.projects.map(mk))}
function renderKanban(){const root=$('#kanban');root.replaceChildren(...stages.map(st=>{const col=document.createElement('div');col.className='kanban-col';const arr=state.opps.filter(o=>o.stage===st);const head=document.createElement('div');head.className='kanban-head';const b=document.createElement('b');b.textContent=st;const s=document.createElement('span');s.textContent=`${fa(arr.length)} • ${irr(arr.reduce((x,o)=>x+o.amount,0))}`;head.append(b,s);col.append(head);arr.forEach(o=>{const c=document.createElement('div');c.className='deal-card'+(o.hot?' hot':'');c.draggable=true;c.dataset.id=o.id;const h=document.createElement('h3');h.textContent=o.title;const ac=document.createElement('div');ac.className='account';ac.textContent=account(o.account).name;const meta=document.createElement('div');meta.className='deal-meta';const m1=document.createElement('span');m1.textContent=irr(o.amount);const m2=document.createElement('span');m2.textContent=`${fa(o.prob)}٪`;meta.append(m1,m2);const n=document.createElement('div');n.className='deal-next';n.textContent=`اقدام بعدی: ${o.next} • ${o.due}`;c.append(h,ac,meta,n);c.ondragstart=e=>e.dataTransfer.setData('text/plain',o.id);col.append(c)});col.ondragover=e=>e.preventDefault();col.ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain'),o=state.opps.find(x=>x.id===id);if(o&&o.stage!==st){o.stage=st;renderAll()}};return col}));$('#pipelineTotal').textContent=`ارزش کل: ${irr(state.opps.reduce((s,o)=>s+o.amount,0))}`}
function renderCustomers(selected='a1'){const list=$('#customerList');list.replaceChildren(...state.accounts.map(a=>{const d=document.createElement('div');d.className='customer-row'+(a.id===selected?' active':'');const h=document.createElement('h3');h.textContent=a.name;const p=document.createElement('p');p.textContent=`${a.type} • ${a.city} • ${a.phone}`;d.append(h,p);d.onclick=()=>renderCustomers(a.id);return d}));render360(selected)}
function render360(id){const a=account(id),opps=state.opps.filter(o=>o.account===id),projects=state.projects.filter(p=>p.account===id),root=$('#customer360');root.replaceChildren();const head=document.createElement('div');head.className='profile-head';const tt=document.createElement('div');tt.className='profile-title';const h=document.createElement('h2');h.textContent=a.name;const p=document.createElement('p');p.textContent=`${a.type} • ${a.city} • ${a.phone}`;tt.append(h,p);const acts=document.createElement('div');acts.className='profile-actions';['☎ تماس','واتساپ','＋ پیگیری'].forEach(x=>{const b=document.createElement('button');b.className='secondary';b.textContent=x;acts.append(b)});head.append(tt,acts);root.append(head);
const sums=[['فرصت باز',fa(opps.length)],['ارزش فرصت‌ها',irr(opps.reduce((s,o)=>s+o.amount,0))],['پروژه فعال',fa(projects.length)],['اقدام بعدی',opps[0]?.next||'—']];const sg=document.createElement('div');sg.className='summary-grid';sums.forEach(([l,v])=>{const d=document.createElement('div');d.className='summary-box';const s=document.createElement('span');s.textContent=l;const b=document.createElement('b');b.textContent=v;d.append(s,b);sg.append(d)});root.append(sg);
const ch=document.createElement('h3');ch.textContent='افراد مرتبط';root.append(ch);a.contacts.forEach(c=>{const d=document.createElement('div');d.className='customer-row';const b=document.createElement('b');b.textContent=c.name;const p=document.createElement('p');p.textContent=`${c.role} • ${c.mobile}`;d.append(b,p);root.append(d)});
const th=document.createElement('h3');th.textContent='Timeline فعالیت';root.append(th);const tl=document.createElement('div');tl.className='timeline';const items=[['امروز','پیگیری فروش',opps[0]?.next||'اقدام بعدی تعیین نشده'],['۲ روز قبل','تماس','درباره قیمت و زمان تحویل گفتگو شد'],['۵ روز قبل','پیش‌فاکتور','نسخه جدید برای مشتری ارسال شد']];items.forEach(([d,t,desc])=>{const it=document.createElement('div');it.className='timeline-item';const dt=document.createElement('div');dt.className='timeline-date';dt.textContent=d;const line=document.createElement('div');line.className='timeline-line';const ct=document.createElement('div');ct.className='timeline-content';const hh=document.createElement('h4');hh.textContent=t;const pp=document.createElement('p');pp.textContent=desc;ct.append(hh,pp);it.append(dt,line,ct);tl.append(it)});root.append(tl)}
function renderProjects(){const root=$('#projectsGrid');root.replaceChildren(...state.projects.map(p=>{const d=document.createElement('div');d.className='project-big';const h=document.createElement('h3');h.textContent=p.title;const a=document.createElement('p');a.className='muted';a.textContent=`${account(p.account).name} • ${irr(p.amount)}`;const st=document.createElement('b');st.textContent=`مرحله فعلی: ${p.stage}`;const steps=document.createElement('div');steps.className='stage-steps';for(let i=0;i<p.total;i++){const x=document.createElement('i');if(i<p.progress)x.className='done';steps.append(x)}d.append(h,a,st,steps);return d}))}
function renderActivitiesTable(){const wrap=$('#activitiesTable');const table=document.createElement('table');table.className='activity-table';const tr=document.createElement('tr');['زمان','نوع','موضوع','مشتری','وضعیت'].forEach(x=>{const th=document.createElement('th');th.textContent=x;tr.append(th)});table.append(tr);state.activities.forEach(x=>{const r=document.createElement('tr');[x.time,x.type,x.subject,account(x.account).name,x.overdue?'عقب‌افتاده':'برنامه‌ریزی شده'].forEach(v=>{const td=document.createElement('td');td.textContent=v;r.append(td)});table.append(r)});wrap.replaceChildren(table)}
function modal(htmlBuilder){$('#modalContent').replaceChildren();htmlBuilder($('#modalContent'));$('#modalBackdrop').classList.remove('hidden')}function closeModal(){$('#modalBackdrop').classList.add('hidden')}$('#modalClose').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};
function field(label,type='text'){const d=document.createElement('div');d.className='field';const l=document.createElement('label');l.textContent=label;const i=document.createElement('input');i.type=type;d.append(l,i);return [d,i]}
function openQuick(){modal(root=>{const h=document.createElement('h2');h.textContent='ثبت سریع';const p=document.createElement('p');p.className='muted';p.textContent='بدون خروج از صفحه، اقدام بعدی را ثبت کن.';const g=document.createElement('div');g.className='form-grid';const [f1,s1]=field('عنوان پیگیری');const [f2,s2]=field('زمان','datetime-local');const [f3,s3]=field('مشتری');f3.classList.add('full');g.append(f1,f2,f3);const actions=document.createElement('div');actions.className='modal-actions';const save=document.createElement('button');save.className='primary';save.textContent='ثبت پیگیری';save.onclick=()=>{if(!s1.value.trim())return;s1.value='';closeModal()};actions.append(save);root.append(h,p,g,actions)})}
function openResult(x){modal(root=>{const h=document.createElement('h2');h.textContent='نتیجه پیگیری';const p=document.createElement('p');p.className='muted';p.textContent=x.subject;const g=document.createElement('div');g.className='form-grid';const [r1,i1]=field('نتیجه');const [r2,i2]=field('اقدام بعدی');const [r3,i3]=field('زمان اقدام بعدی','datetime-local');r2.classList.add('full');r3.classList.add('full');g.append(r1,r2,r3);const ac=document.createElement('div');ac.className='modal-actions';const save=document.createElement('button');save.className='primary';save.textContent='ثبت و تکمیل';save.onclick=()=>{x.overdue=false;x.time='انجام شد';closeModal();renderActivities();renderActivitiesTable();renderKPIs()};ac.append(save);root.append(h,p,g,ac)})}
$('#quickAdd').onclick=openQuick;$('#newOpportunity').onclick=openQuick;$('#newCustomer').onclick=openQuick;
$('#search').oninput=e=>{const q=e.target.value.trim().toLowerCase();if(!q)return;const a=state.accounts.find(x=>[x.name,x.phone,x.city,...x.contacts.flatMap(c=>[c.name,c.mobile])].join(' ').toLowerCase().includes(q));if(a){nav('customers');renderCustomers(a.id)}};
function renderAll(){renderKPIs();renderMiniPipeline();renderActivities();renderRisk();renderProjectsStrip();renderKanban();renderCustomers();renderProjects();renderActivitiesTable()}renderAll();