const STORAGE_KEY='namiwin-crm-v2-state';
const projectStages=['پیش‌اندازه‌گیری / دریافت لیست','پیش‌فاکتور','جلسه قرارداد','کارشناسی زیرسازی','اندازه‌گیری نهایی','تولید','اندازه‌گیری شیشه','ارسال بار','حمل و توزیع طبقات','نصب','اندازه‌گیری شیشه مجدد','ارسال و توزیع شیشه','نصب شیشه','تحویل موقت','چسب، لاستیک و آب‌بندی','ریگلاژ و تحویل نهایی'];
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify({accounts:state.accounts,opps:state.opps,activities:state.activities,projects:state.projects}))}
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return;const x=JSON.parse(raw);['accounts','opps','activities','projects'].forEach(k=>{if(Array.isArray(x[k]))state[k].splice(0,state[k].length,...x[k])})}catch(e){console.warn('state restore failed',e)}}
function makeId(prefix){return prefix+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function mkField(label,type='text',value=''){const wrap=document.createElement('div');wrap.className='field';const l=document.createElement('label');l.textContent=label;let el;if(type==='select'){el=document.createElement('select')}else if(type==='textarea'){el=document.createElement('textarea')}else{el=document.createElement('input');el.type=type}if(value)el.value=value;wrap.append(l,el);return [wrap,el]}
function option(sel,value,text=value){const o=document.createElement('option');o.value=value;o.textContent=text;sel.append(o)}
function openNewCustomer(){modal(root=>{const h=document.createElement('h2');h.textContent='مشتری / شرکت جدید';const g=document.createElement('div');g.className='form-grid';const [f1,name]=mkField('نام مشتری یا شرکت');const [f2,type]=mkField('نوع','select');['سازنده','مالک','معمار','انبوه‌ساز','مجری','شرکت','سایر'].forEach(x=>option(type,x));const [f3,phone]=mkField('موبایل / تلفن');const [f4,city]=mkField('شهر');const [f5,source]=mkField('منبع سرنخ');const [f6,notes]=mkField('یادداشت','textarea');f6.classList.add('full');g.append(f1,f2,f3,f4,f5,f6);const actions=document.createElement('div');actions.className='modal-actions';const save=document.createElement('button');save.className='primary';save.textContent='ثبت مشتری';save.onclick=()=>{if(!name.value.trim())return alert('نام مشتری الزامی است');const duplicate=state.accounts.find(a=>a.phone&&phone.value&&a.phone===phone.value.trim());if(duplicate)return alert('این شماره قبلاً برای '+duplicate.name+' ثبت شده است');const id=makeId('a');state.accounts.unshift({id,name:name.value.trim(),type:type.value,phone:phone.value.trim(),city:city.value.trim()||'اصفهان',source:source.value.trim(),notes:notes.value.trim(),contacts:[]});saveState();closeModal();renderAll();nav('customers');renderCustomers(id)};actions.append(save);root.append(h,g,actions)})}
function openNewOpportunity(){if(!state.accounts.length)return openNewCustomer();modal(root=>{const h=document.createElement('h2');h.textContent='فرصت فروش جدید';const g=document.createElement('div');g.className='form-grid';const [f1,title]=mkField('عنوان پروژه / فرصت');const [f2,acc]=mkField('مشتری','select');state.accounts.forEach(a=>option(acc,a.id,a.name));const [f3,stage]=mkField('مرحله','select');stages.forEach(x=>option(stage,x));const [f4,amount]=mkField('مبلغ احتمالی - ریال','number');const [f5,prob]=mkField('احتمال موفقیت %','number','20');const [f6,next]=mkField('اقدام بعدی');const [f7,due]=mkField('زمان اقدام بعدی','datetime-local');f6.classList.add('full');f7.classList.add('full');g.append(f1,f2,f3,f4,f5,f6,f7);const actions=document.createElement('div');actions.className='modal-actions';const save=document.createElement('button');save.className='primary';save.textContent='ثبت فرصت';save.onclick=()=>{if(!title.value.trim())return alert('عنوان فرصت الزامی است');if(!next.value.trim())return alert('برای هر فرصت باز، اقدام بعدی الزامی است');if(!due.value)return alert('زمان اقدام بعدی را مشخص کن');const p=Math.max(0,Math.min(100,Number(prob.value||0))),id=makeId('o');state.opps.unshift({id,account:acc.value,title:title.value.trim(),stage:stage.value,amount:Number(amount.value||0),prob:p,next:next.value.trim(),due:new Date(due.value).toLocaleString('fa-IR'),lastDays:0,hot:p>=70});state.activities.unshift({id:makeId('t'),time:new Date(due.value).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'}),account:acc.value,subject:next.value.trim(),type:'پیگیری',overdue:new Date(due.value)<new Date()});saveState();closeModal();renderAll();nav('pipeline')};actions.append(save);root.append(h,g,actions)})}
function openQuickChoice(){modal(root=>{const h=document.createElement('h2');h.textContent='ثبت سریع';const p=document.createElement('p');p.className='muted';p.textContent='چه چیزی می‌خواهی ثبت کنی؟';const box=document.createElement('div');box.className='project-strip';[['مشتری جدید',openNewCustomer],['فرصت فروش',openNewOpportunity],['پیگیری',()=>{closeModal();openQuick()}]].forEach(([label,fn])=>{const b=document.createElement('button');b.className='secondary';b.textContent='＋ '+label;b.onclick=()=>{closeModal();fn()};box.append(b)});root.append(h,p,box)})}
function convertWon(opp){if(state.projects.some(p=>p.opportunityId===opp.id))return;state.projects.unshift({id:makeId('p'),account:opp.account,opportunityId:opp.id,title:opp.title,stage:projectStages[0],progress:1,total:projectStages.length,amount:opp.amount});opp.status='won';opp.prob=100;opp.stage='جلسه قرارداد';opp.next='شروع پروژه اجرایی';opp.due='ایجاد شد';saveState();renderAll();nav('projects')}
function openDealActions(opp){modal(root=>{const h=document.createElement('h2');h.textContent=opp.title;const p=document.createElement('p');p.className='muted';p.textContent=`${account(opp.account).name} • ${irr(opp.amount)} • احتمال ${fa(opp.prob)}٪`;const g=document.createElement('div');g.className='form-grid';const [f1,next]=mkField('اقدام بعدی','text',opp.next||'');const [f2,due]=mkField('زمان اقدام بعدی','datetime-local');const [f3,prob]=mkField('احتمال %','number',String(opp.prob));const [f4,lost]=mkField('علت باخت','select');['','قیمت','رقیب','زمان تحویل','پروژه متوقف شد','عدم تأمین مالی','عدم پیگیری','سایر'].forEach(x=>option(lost,x,x||'انتخاب علت باخت'));f1.classList.add('full');g.append(f1,f2,f3,f4);const actions=document.createElement('div');actions.className='modal-actions';const update=document.createElement('button');update.className='secondary';update.textContent='ذخیره تغییرات';update.onclick=()=>{if(!next.value.trim())return alert('اقدام بعدی الزامی است');opp.next=next.value.trim();opp.prob=Math.max(0,Math.min(100,Number(prob.value||0)));opp.hot=opp.prob>=70;if(due.value)opp.due=new Date(due.value).toLocaleString('fa-IR');saveState();closeModal();renderAll()};const lose=document.createElement('button');lose.className='secondary';lose.textContent='باخته شد';lose.onclick=()=>{if(!lost.value)return alert('علت باخت را مشخص کن');opp.status='lost';opp.lostReason=lost.value;state.opps.splice(state.opps.indexOf(opp),1);saveState();closeModal();renderAll()};const won=document.createElement('button');won.className='primary';won.textContent='قرارداد شد → پروژه';won.onclick=()=>{closeModal();convertWon(opp)};actions.append(update,lose,won);root.append(h,p,g,actions)})}
loadState();renderAll();
$('#quickAdd').onclick=openQuickChoice;$('#newOpportunity').onclick=openNewOpportunity;$('#newCustomer').onclick=openNewCustomer;
$('#kanban').addEventListener('click',e=>{const card=e.target.closest('.deal-card');if(!card)return;const opp=state.opps.find(o=>o.id===card.dataset.id);if(opp)openDealActions(opp)});
const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();saveState()};