<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>NamiWinCRM</RootNamespace>
    <AssemblyName>NamiWin-CRM-Windows-Portable</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
</Project>
